### ISSUE TITLE
DB_Monitoring

### ISSUE THREAD

**Issue by lRuslanl** [132sergey132/VirtualizationApp_Monitoring#2]
CREATE TABLE Metric
(
id_metric INT,
value VARCHAR2(100),
dateMetric DATE,
id_metric_type INT,
constraint PK_Metric primary key(id_metric),
constraint FK_Metric_Type foreign key (id_metric_type) references Metric_Type(id_metric_type)
);
/
CREATE TABLE Metric_Type
(
id_metric_type INT,
type_metric VARCHAR2(100),
constraint PK_Metric_Type primary key(id_metric_type)
);
/
CREATE TABLE SNMP_Params
(
id_snmp_params INT,
udpheader VARCHAR2(100),
community VARCHAR2(100),
pdu_type VARCHAR2(100),
id_metric_type INT,
constraint PK_SNMP_Params primary key(id_snmp_params),
constraint FK_Metric_Type foreign key (id_metric_type) references Metric_Type(id_metric_type)
);
/
CREATE TABLE Treshhold
(
id_m_type INT,
id_policy INT,
sign VARCHAR2(100),
value VARCHAR2(100),
constraint PK_Treshhold primary key(id_m_type, id_policy),
constraint FK_Metric_Type foreign key(id_m_type) references Metric_Type(id_metric_type),
constraint FK_Policy foreign key(id_policy) references Policy(id_policy)
);
/
CREATE TABLE Policy
(
id_policy INT,
id_policy_list INT,
id_metric_type INT,
id_event_type INT,
constraint PK_Policy primary key(id_policy),
constraint FK_Policy_List foreign key (id_policy_list) references Policy_List(id_policy_list),
constraint FK_Metric_type foreign key (id_metric_type) references Metric_Type(id_metric_type),
constraint FK_Event_Type foreign key (id_event_type) references Event_Type(id_event_type)
);
/
CREATE TABLE Event_Type
(
id_event_type INT,
type VARCHAR2(100),
priority INT,
constraint PK_Event_Type primary key (id_event_type)
);
/
CREATE TABLE Event
(
id_event INT,
date_event DATE,
message VARCHAR2(100),
id_event_type INT,
constraint PK_Event primary key (id_event),
constraint FK_Event_Type foreign key (id_event_type) references Event_Type(id_event_type)
);
/
CREATE TABLE Policy_Action
(
id_policy INT,
id_action INT,
constraint FK_Policy foreign key (id_policy) references Policy(id_policy),
constraint FK_Action foreign key (id_action) references Action(id_action)
);
/
CREATE TABLE Action
(
id_action INT,
type VARCHAR2(100),
constraint PK_Action primary key (id_action)
);
/
CREATE TABLE Policy_List
(
id_policy_list INT,
id_profile,
constraint PK_Policy_List primary key (id_policy_list),
constraint FK_Profile foreign key (id_profile) references Profile(id_profile)
);
/
CREATE TABLE Profile
(
id_profile INT,
name VARCHAR2(100),
constraint PK_Profile primary key (id_profile)
);
/
CREATE TABLE VM
(
id_vm INT,
name VARCHAR2(100),
date_vm DATE,
ip VARCHAR2(40),
image VARCHAR(100),
ext_id INT,
id_pm INT,
id_profile INT,
constraint PK_VM primary key (id_vm),
constraint FK_PM foreign key (id_pm) references PM(id_pm),
constraint FK_Profile foreign key (id_profile) references Profile(id_profile)
);
/
CREATE TABLE logs
(
id_logs INT,
text VARCHAR2(100),
obj_id VARCHAR2(100),
id_vm INT,
constraint PK_logs primary key (id_logs),
constraint FK_VM foreign key (id_vm) references VM(id_vm)
);
/
CREATE TABLE PM
(
id_pm INT,
ip VARCHAR2(40),
date_pm DATE,
constraint PK_PM primary key (id_pm)
);
/
CREATE TABLE VNF
(
id_vnf INT,
date_vnf DATE,
type_vnf VARCHAR2(100),
script VARCHAR2(100),
id_vm INT,
constraint PK_VNF primary key (id_vnf),
constraint FK_VM foreign key (id_vm) references VM(id_vm)
);

**Comment by Nimtar** [comment]
Для удобства сверки
![](https://pp.vk.me/c636825/v636825630/306a5/G6iD10OP1ms.jpg)
